/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coding.problems.java;

public class App {
    public static void main(String[] args) {
        Leetcode1ProblemTwoSum.main(new String[]{});
    }
}
