/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.structures.java.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test void testNotNull() {
        assertNotNull(new App());
    }
}
